"""Turning a document number into something that may be written down.

The only door from a :class:`~core.privacy.identifiers.RawIdentifier` to a
value that can be persisted, indexed or compared. Everything stored is the
output of this module; the input never is.

**This is pseudonymisation, not anonymisation, and the difference matters
here.** An Aadhaar number has about 9x10^11 possible values. That is a small
space: given the digest of one and the secret used to produce it, every
candidate can be tried until one matches, on ordinary hardware, quickly. No
choice of hash function changes that, because the keyspace of the *input* is
what is small.

Two things follow, and both are design constraints rather than caveats:

* The secret must be a **key**, not a salt. A salt is unique but public, and is
  normally stored beside the data it protects; that would leave the digests
  reversible by anyone who obtained the database. This module uses HMAC-SHA256
  with a per-deployment key that must be held outside the database.
* Compromise of **both** the key and the database recovers every number. Say so
  in any privacy assessment. Describing these digests as anonymous would be the
  same error as calling a face embedding irreversible, which rule 4 of
  CLAUDE.md forbids for the same reason.

Digests are domain-separated by document kind, so the same digits recorded as a
voter card number and as a driving licence number produce different values and
do not silently link two unrelated records.
"""

from __future__ import annotations

import hashlib
import hmac
import secrets
from typing import Final

from core.privacy.identifiers import RawIdentifier

MINIMUM_KEY_BYTES: Final[int] = 32
"""Shortest accepted key. Matches the SHA-256 block security level."""

DIGEST_LENGTH: Final[int] = 64
"""Length of a digest in hexadecimal characters."""

_SEPARATOR: Final[str] = ":"
"""Separates the domain label from the value. Not part of either."""


class DeploymentKey:
    """The per-deployment secret used to derive identifier digests.

    Held outside the database. Rotating it changes every digest, which breaks
    historical matching — that is a deployment decision, not something this
    class hides.

    The key material never leaves the object: callers ask it to derive a
    digest rather than reading the bytes out.
    """

    __slots__ = ("_material",)

    def __init__(self, material: bytes) -> None:
        """Hold key material.

        Args:
            material: At least :data:`MINIMUM_KEY_BYTES` bytes of secret,
                generated by a cryptographically secure source.

        Raises:
            ValueError: If the material is too short.
        """
        if len(material) < MINIMUM_KEY_BYTES:
            msg = f"a deployment key must be at least {MINIMUM_KEY_BYTES} bytes"
            raise ValueError(msg)
        self._material = material

    @classmethod
    def generate(cls) -> DeploymentKey:
        """Return a new key from the system's secure random source.

        Returns:
            A fresh key. Store it outside the database and back it up: losing
            it makes every existing digest unmatchable.
        """
        return cls(secrets.token_bytes(MINIMUM_KEY_BYTES))

    def derive(self, payload: bytes) -> str:
        """Return the keyed digest of a payload.

        Args:
            payload: The bytes to authenticate.

        Returns:
            Lowercase hexadecimal HMAC-SHA256, the same shape as every other
            digest in the system.
        """
        return hmac.new(self._material, payload, hashlib.sha256).hexdigest()

    def __repr__(self) -> str:
        """Return a redacted form, so a key never reaches a traceback or a log."""
        return "DeploymentKey(<redacted>)"

    __str__ = __repr__


def hash_document_number(identifier: RawIdentifier, *, key: DeploymentKey) -> str:
    """Return the persistable digest of a document number.

    Args:
        identifier: The number in the clear.
        key: The per-deployment secret.

    Returns:
        Lowercase hexadecimal HMAC-SHA256 over the document kind and the
        normalised number. This is what may be stored; the argument is not.
    """
    payload = f"{identifier.kind.value}{_SEPARATOR}{identifier.reveal()}".encode()
    return key.derive(payload)


def digests_match(left: str, right: str) -> bool:
    """Compare two digests without leaking their contents through timing.

    Ordinary string comparison returns as soon as it finds a difference, which
    tells an attacker who can measure it how much of a guess was correct. That
    matters from phase 8, where digests are compared to find repeat crossings.

    Args:
        left: One digest.
        right: The other.

    Returns:
        Whether they are equal.
    """
    return hmac.compare_digest(left, right)
