#!/usr/bin/env python3
"""Run the whole story once, offline, and print what an officer would see.

    python tools/demo.py

Everything happens in a throwaway database under `--work`, so it can be run
repeatedly, and it needs no network, no phone, no browser and no server. That is
the point: **this is the demonstration that cannot fail on the day.** If the
projector is offline, the wifi is hostile or the laptop is not the one that was
set up, this still runs.

It walks the five things worth showing, in order:

1. A genuine synthetic document is screened. It is not cleared, and the report
   says exactly what could not be checked.
2. A forged document is screened. The tamper detector escalates it and states,
   in the same breath, that its finding is not proof.
3. An officer overrides a case. The verdict is not rewritten; a second record is
   appended beside it.
4. A checkpoint is published and a series is chained, so the log's growth is
   provable.
5. A third party verifies that series with `tools/verify_checkpoint.py`, which
   imports nothing from this system.

Nothing here invents a number. Every line printed is produced by the code being
demonstrated, on documents this repository generated.
"""

from __future__ import annotations

import argparse
import datetime
import json
import pathlib
import shutil
import subprocess
import sys
import tempfile

BANNER = "=" * 78
"""Wide enough to read from the back of a room."""


def heading(number: int, title: str) -> None:
    """Print a section heading."""
    print(f"\n{BANNER}\n  {number}.  {title}\n{BANNER}")


def indent(text: str, prefix: str = "      ") -> str:
    """Indent a block so it reads as output rather than narration."""
    return "\n".join(prefix + line if line.strip() else line for line in text.splitlines())


def main(argv: list[str] | None = None) -> int:
    """Run the demonstration and return a process exit code."""
    parser = argparse.ArgumentParser(
        prog="python tools/demo.py",
        description="Run the SENTINEL ID demonstration end to end, offline.",
    )
    parser.add_argument(
        "--work",
        default=None,
        help="Working directory. A temporary one is used and removed if omitted.",
    )
    parser.add_argument(
        "--keep",
        action="store_true",
        help="Keep the working directory so the files can be inspected afterwards.",
    )
    arguments = parser.parse_args(argv)

    temporary = arguments.work is None
    work = pathlib.Path(arguments.work or tempfile.mkdtemp(prefix="sentinelid-demo-"))
    work.mkdir(parents=True, exist_ok=True)

    try:
        return _run(work)
    finally:
        if temporary and not arguments.keep:
            shutil.rmtree(work, ignore_errors=True)
        else:
            print(f"\nWorking files kept in {work}")


# A long function on purpose: this is a narrated script, meant to be read
# top to bottom in the same order it prints.
def _run(work: pathlib.Path) -> int:
    """Perform the demonstration inside a working directory."""
    import secrets

    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

    from api.intake import record_capture
    from api.screening import Deployment
    from api.settings import Settings
    from core.contracts import Decision, DocumentType, OfficerReview
    from datagen.forgeries.recapture import Recapture
    from datagen.synthetic_docs import generate_specimen
    from db.recording import load_case, load_log, record_review
    from db.session import create_session_factory
    from explain.renderer import render_verdict
    from ledger.hashchain import verify_consistency

    print(BANNER)
    print("  SENTINEL ID - screening demonstration")
    print("  Every document below was generated by this repository. No real")
    print("  document has ever been screened by this system.")
    print(BANNER)

    ledger_key_path = work / "ledger.pem"
    ledger_key = Ed25519PrivateKey.generate()
    ledger_key_path.write_bytes(
        ledger_key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption(),
        )
    )
    hash_key_path = work / "hash.key"
    hash_key_path.write_bytes(secrets.token_bytes(32))

    database = work / "demo.sqlite3"
    settings = Settings(
        database_url=f"sqlite+pysqlite:///{database.as_posix()}",
        checkpoint_id="DEMO-CROSSING-01",
        ledger_key=ledger_key,
    )
    factory = create_session_factory(settings.database_url, create=True)
    deployment = Deployment(settings=settings)

    print("\n  This checkpoint is not fully equipped, and says so:")
    for line in settings.unavailable():
        print(f"    - {line}")

    # 1. A genuine document
    heading(1, "A genuine document is screened")
    specimen = generate_specimen(seed=20260910)
    now = datetime.datetime.now(tz=datetime.UTC)
    with factory() as session:
        genuine = record_capture(
            session,
            specimen.png,
            case_id="DEMO-0001",
            settings=settings,
            deployment=deployment,
            now=now,
            media_type="image/png",
            declared_type=DocumentType.INDIAN_PASSPORT,
        )
    print(f"\n  Decision: {genuine.verdict.decision.value}")
    print(f"  Not checked: {len(genuine.verdict.not_checked)} things\n")
    print(indent(render_verdict(genuine.verdict)))

    # 2. A forgery
    heading(2, "A forged document is screened")
    forgery = Recapture()
    forged_png = forgery.apply(specimen, seed=20260910)
    print(f"\n  Forgery applied: {forgery.alters}")
    with factory() as session:
        tampered = record_capture(
            session,
            forged_png,
            case_id="DEMO-0002",
            settings=settings,
            deployment=deployment,
            now=now + datetime.timedelta(minutes=1),
            media_type="image/png",
            declared_type=DocumentType.INDIAN_PASSPORT,
        )
    print(f"  Decision: {tampered.verdict.decision.value}\n")
    for finding in tampered.verdict.findings:
        print(f"  [{finding.severity.name}] {finding.headline}")
        for line in finding.detail:
            print(f"      {line}")
        if finding.standard_ref:
            print(f"      Standard: {finding.standard_ref}")

    # 3. An officer decides
    heading(3, "An officer overrides the system, and it is recorded beside it")
    with factory() as session:
        record_review(
            session,
            OfficerReview(
                case_id="DEMO-0002",
                outcome=Decision.REJECTED,
                officer_id="officer-14",
                note="Bearer could not explain the discrepancy. Referred to supervisor.",
                system_decision=tampered.verdict.decision,
                recorded_at=now + datetime.timedelta(minutes=5),
            ),
        )
        view = load_case(session, "DEMO-0002")

    if view is None:  # pragma: no cover - it was written a line ago
        print("  The case could not be read back. That is a defect, not a demonstration.")
        return 1
    print(f"\n  What the system decided : {view.verdict.decision.value}")
    print(f"  What the officer decided: {view.standing_decision.value}")
    print(f"  Decided by              : {view.reviews[-1].officer_id}")
    print("\n  The verdict was not rewritten. The officer's decision is a second")
    print("  record. Overwriting the first is the tamper this log exists to catch.")

    # 4. Publish a chained series
    heading(4, "Checkpoints are published, each proving it extends the last")
    checkpoints = work / "checkpoints"
    checkpoints.mkdir(exist_ok=True)
    environment = {
        "SENTINELID_DB_URL": settings.database_url,
        "SENTINELID_CHECKPOINT_ID": settings.checkpoint_id,
        "SENTINELID_LEDGER_KEY_FILE": str(ledger_key_path),
    }
    import os

    saved = {name: os.environ.get(name) for name in environment}
    os.environ.update(environment)
    try:
        from api import publish_checkpoint

        publish_checkpoint.main(["--out", str(checkpoints)])
        first = sorted(checkpoints.glob("*.json"))[0]

        with factory() as session:
            record_capture(
                session,
                specimen.png,
                case_id="DEMO-0003",
                settings=settings,
                deployment=deployment,
                now=now + datetime.timedelta(minutes=10),
                media_type="image/png",
            )
        publish_checkpoint.main(["--out", str(checkpoints), "--since", str(first)])
    finally:
        for name, value in saved.items():
            if value is None:
                os.environ.pop(name, None)
            else:
                os.environ[name] = value

    published = sorted(checkpoints.glob("*.json"))

    with factory() as session:
        log = load_log(session)
    earlier = json.loads(published[0].read_text(encoding="utf-8"))
    later = json.loads(published[1].read_text(encoding="utf-8"))
    proved = verify_consistency(
        old_size=int(earlier["tree_size"]),
        new_size=int(later["tree_size"]),
        old_root=bytes.fromhex(earlier["root"]),
        new_root=bytes.fromhex(later["root"]),
        proof=tuple(bytes.fromhex(node) for node in later["consistency"]["proof"]),
    )
    print(f"\n  Log now holds {len(log)} entries.")
    print(f"  Consistency between the two published checkpoints: {proved}")

    # 5. A third party checks it
    heading(5, "A third party verifies the log, using none of this system")
    tool = pathlib.Path(__file__).with_name("verify_checkpoint.py")
    finished = subprocess.run(  # noqa: S603
        [sys.executable, str(tool), *[str(path) for path in published]],
        capture_output=True,
        text=True,
        check=False,
    )
    print(indent(finished.stdout.rstrip()))
    if finished.returncode != 0:
        print(indent(finished.stderr.rstrip()))
        print("\n  VERIFICATION FAILED. This is a defect, not a demonstration.")
        return 1

    print("\n" + BANNER)
    print("  What this showed")
    print(BANNER)
    print("  - Nothing was cleared. Rung 0 holds no issuer keys here, so no")
    print("    document can be confirmed genuine, and every case says so.")
    print("  - The forgery was escalated to a person, never condemned by the")
    print("    machine on its own.")
    print("  - The officer's decision sits beside the system's, not over it.")
    print("  - The log's growth was proved to somebody holding no database.")
    print(BANNER)
    return 0


if __name__ == "__main__":  # pragma: no cover - the process entry point
    raise SystemExit(main(sys.argv[1:]))
